volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13.10
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: ${DOCKERHUB_USER}/kittygram_backend
    env_file: .env
    volumes:
      - static:/app/static_files
      - media:/app/media
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: ${DOCKERHUB_USER}/kittygram_frontend
    env_file: .env
    volumes:
      - static:/app/build

  gateway:
    build: ./nginx
    image: ${DOCKERHUB_USER}/kittygram_gateway
    ports:
      - "80:80"
    volumes:
      - static:/static_files/  # Монтируем корень тома в отдельную папку
      - media:/media
    depends_on:
      - backend
      - frontend
    networks:
      default:
        aliases:
          - kittygram.local