server {
  listen 80;
  server_tokens off;
  index index.html;

 
  location /static/ {
    # Nginx будет искать файлы в /backend_static/static/
    # URL /static/admin/css/base.css -> путь /backend_static/static/admin/css/base.css
    alias /static_files/static/;
  }
  location /static/admin/ {
    alias /static_files/admin/;
  }
  location /static/rest_framework/ {
    alias /static_files/rest_framework/;
  }

  location /media/ {
    alias /media/;
  }

  location / {
    # Путь к index.html фронтенда
    root /static_files/;
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_pass http://backend:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /admin/ {
    proxy_pass http://backend:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}